### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by yangguohua1993** [volkerschmidts/titania#1]
when I make , I'm having some problems:

```console
/usr/local/titania/titania-1.6.46/src/LinAlg.cpp:229:7: warning: conversion from ‘Eigen::Index’ {aka ‘long int’} to ‘int’ may change value [-Wconversion]
  229 |   int cols = svd.matrixV().rows();
      |       ^~~~
c++: fatal error: killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [src/CMakeFiles/titania_lib.dir/build.make:154：src/CMakeFiles/titania_lib.dir/LinAlg.cpp.o] error 1
make[1]: *** [CMakeFiles/Makefile2:186：src/CMakeFiles/titania_lib.dir/all] error  2
make: *** [Makefile:141：all] error  2
```

my dependencies:
cmake  (3.16.3-1ubuntu1)。
liblapacke-dev  (3.9.0-1build1)。
libcppunit-dev  (1.15.1-2build1)。
libeigen3-dev  (3.3.7-2)。
libnlopt-cxx-dev  (2.6.1-8ubuntu2)。
build-essential  (12.8ubuntu1.1)。

**Comment by volkerschmidts** [comment]
thanks for trying out TITANIA!

The error message says that the compiler received a termination signal. Unless you intentionally killed the process yourself, the only thing I can think of is maybe there was no more memory available to compile the admittetly somewhat large `LinAlg.o`? I only ever tried to compile TITANIA on machines with 8GB RAM or more and never ran into this issue. 

Refactoring this large module into smaller chunks is on the TODO list.

**Comment by yangguohua1993** [comment]
Thank you for your answer. I completed the installation by expanding the memory to 6G。
